# Generated by Django 3.0.7 on 2020-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('anh', models.ImageField(upload_to='')),
                ('gia', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='hinhanh',
        ),
    ]
